import type { Metadata } from 'next';
import { Questrial } from 'next/font/google';
import './globals.css';
import TopHeader from '@/components/layout/TopHeader';

// Using Google Font Fallback (Questrial) for Century Gothic
const questrial = Questrial({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-questrial',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${questrial.variable} h-full antialiased`}>
      <body className="font-sans min-h-full flex flex-col">
        <TopHeader />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
